"""說明文字

Revision ID: 4f2bb0bc3192
Revises: 
Create Date: 2022-08-25 18:00:37.887510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2bb0bc3192'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserReister',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('userid')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('body', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('postid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_timestamp'), 'message', ['timestamp'], unique=False)
    op.create_table('spot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('head', sa.String(length=100), nullable=True),
    sa.Column('main', sa.String(length=100), nullable=True),
    sa.Column('pic', sa.String(length=100), nullable=True),
    sa.Column('tag', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('body', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggest_timestamp'), 'suggest', ['timestamp'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('head', sa.String(length=64), nullable=True),
    sa.Column('main', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Date(), nullable=True),
    sa.Column('tag', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=80), nullable=True),
    sa.Column('like', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['UserReister.userid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.create_table('saves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('head', sa.String(length=64), nullable=True),
    sa.Column('main', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Date(), nullable=True),
    sa.Column('tag', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['UserReister.userid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saves_timestamp'), 'saves', ['timestamp'], unique=False)
    op.create_table('collect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postid', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['UserReister.userid'], ),
    sa.ForeignKeyConstraint(['postid'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postid', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['UserReister.userid'], ),
    sa.ForeignKeyConstraint(['postid'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    op.drop_table('collect')
    op.drop_index(op.f('ix_saves_timestamp'), table_name='saves')
    op.drop_table('saves')
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_suggest_timestamp'), table_name='suggest')
    op.drop_table('suggest')
    op.drop_table('spot')
    op.drop_index(op.f('ix_message_timestamp'), table_name='message')
    op.drop_table('message')
    op.drop_table('UserReister')
    # ### end Alembic commands ###
